name: deploy to prod 8600
on:
  push:
    branches: [master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: |
          cd /apps/github-workflows/kenyaemr-modules
          sudo rm -rf openmrs-module-kenyaemrorderentry
          sudo mkdir openmrs-module-kenyaemrorderentry
          sudo chown -R cicd2:cicd2 openmrs-module-kenyaemrorderentry
          git config --global --add safe.directory /apps/github-workflows/kenyaemr-modules/openmrs-module-kenyaemrorderentry
          git clone https://github.com/palladiumkenya/openmrs-module-kenyaemrorderentry.git
          cd /apps/github-workflows/kenyaemr-modules/openmrs-module-kenyaemrorderentry
          git status
          sudo mvn clean install -DskipTests
          sudo rm -rf /var/lib/OpenMRS/modules/kenyaemrorderentry-*.omod
          sudo cp /apps/github-workflows/kenyaemr-modules/openmrs-module-kenyaemrorderentry/omod/target/kenyaemrorderentry-*.omod /var/lib/OpenMRS/modules/
          sudo chown -R tomcat:tomcat /var/lib/OpenMRS/modules/
          sudo chmod +r /var/lib/OpenMRS/modules/*.omod
          sudo systemctl stop tomcat
          sudo systemctl start tomcat
         
